### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [cyrusclarke/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by cyrusclarke** [comment]
Thanks for that Ken, I hadn't tested on mobile or on the chrome inspector tool (was just resizing the browser!)

Think it looks better now with the meta tag in the head.

**Comment by kenmazaika** [comment]
Looks great.  Thumbs up, Cyrus.  :+1:
